on: 
  push:
    branches:
    - main
name: ðŸ”ƒ AtualizaÃ§Ã£o ( PROD )
jobs:
  web-deploy:
    name:  ðŸ“‚ Verificando arquivos
    runs-on: ubuntu-latest
    steps:
    - name: ðŸ“‚ Atualizando
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sincronizando com o servidor
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server:  ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        port: 2121 
 