on: 
  push:
    branches:
    - main
name: ğŸ”ƒ AtualizaÃ§Ã£o iniciada ( PROD )
jobs:
  web-deploy:
    name:  ğŸ“‚ Verificando arquivos
    runs-on: ubuntu-latest
    steps:
    - name: â¬†ï¸ğŸ“‚ Carregando arquivos locais
      uses: actions/checkout@v2
    
    - name: ğŸ”€ğŸ“‚ Sincronizando com o servidor
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server:  ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        port: 2121
 